name: Coverage API CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build docker stack
      run: docker-compose -f local.yml build
    - name: Run Tests
      run: docker-compose -f local.yml run --rm app go test -v ./...